### ISSUE TITLE
Lets get this into ansible galaxy

### ISSUE THREAD

**Issue by JAORMX** [nkinder/ansible-keycloak#1]
It would make it easier to install if this was in ansible galaxy. Here are the steps:

https://galaxy.ansible.com/docs/contributing/creating_role.html

**Comment by moisesguimaraes** [comment]
Done =D

ansible-galaxy install moisesguimaraes.keycloak

@nkinder could you also import this repo in your ansible galaxy? Travis already notifies galaxy, so I don't think you would have to do more than the first import. After that we can also install with nkinder.keycloak.

**Comment by nkinder** [comment]
@moisesguimaraes I have imported it into my galaxy.
