### ISSUE TITLE
Keycloak not started during force reinstallation

### ISSUE THREAD

**Issue by evgeniy-pupkov** [nkinder/ansible-keycloak#17]
Hello! 
When trying to re-install keycloak using *keycloak_force_install=true* variable, playbook gets stuck on "wait for Keycloak management interface to be available" step. The reason is that restart handlers are not triggered, as systemd keyclaok service file left unchanged.
I've achieved it working by adding
```yml
  notify:
      - restart keycloak
``` 
into " extract Keycloak archive on target" and " extract Keycloak archive on local" steps.

**Comment by nkinder** [comment]
Thanks for reporting the issue!  Do you mind submitting a PR for this?

**Comment by nkinder** [comment]
This is resolved by commit b5859343a72c35b2457b1f88d4c5d092bd3131e0.  Thanks for the contribution @evgeniy-pupkov !
